# Generated by Django 2.1.4 on 2019-05-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=256, verbose_name='职位')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automain.Person')),
            ],
            options={
                'permissions': (('create_position', '创建职位'), ('edit_position', '编辑职位'), ('del_position', '删除职位')),
            },
        ),
    ]
