# Generated by Django 2.1.4 on 2019-05-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automain', '0002_personposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personposition',
            options={},
        ),
    ]
