# Generated by Django 2.1.4 on 2019-05-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='事件ID')),
                ('event_type', models.CharField(blank=True, choices=[('delete', '删除'), ('add', '新增'), ('update', '更新')], max_length=10, null=True, verbose_name='事件类型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='数据ID')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='修改对象名称')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='修改的字段名称')),
                ('before_value', models.TextField(blank=True, null=True, verbose_name='修改前的值')),
                ('after_value', models.TextField(blank=True, null=True, verbose_name='修改后的值')),
                ('operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作人')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '日志记录',
            },
        ),
    ]
